package DAO;

public class QUATRINH_NGHIEMTHU_QUYETTOAN {
	private int MA_QUATRINH_NGHIEMTHU_QUYETTOAN;
	private int LOAI_CONGVIEC;

	public int getMA_QUATRINH_NGHIEMTHU_QUYETTOAN() {
		return MA_QUATRINH_NGHIEMTHU_QUYETTOAN;
	}

	public void setMA_QUATRINH_NGHIEMTHU_QUYETTOAN(int mA_QUATRINH_NGHIEMTHU_QUYETTOAN) {
		MA_QUATRINH_NGHIEMTHU_QUYETTOAN = mA_QUATRINH_NGHIEMTHU_QUYETTOAN;
	}

	public final int getLOAI_CONGVIEC() {
		return LOAI_CONGVIEC;
	}

	public final void setLOAI_CONGVIEC(int lOAI_CONGVIEC) {
		LOAI_CONGVIEC = lOAI_CONGVIEC;
	}

}
